=== jtlai0921/PB1436--600-Java----part05-ch15_ch17-/PB1224-5/CH16/462/xmldemo/xsd/attributeGroup_demo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.mingrisoft.com" xmlns="http://www.mingrisoft.com"
	elementFormDefault="qualified">

	<xs:element name="book">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="publisher" type="xs:string" />
				<xs:element name="company" type="xs:string" />
				<xs:element name="author">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attributeGroup ref="att"></xs:attributeGroup>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="ISBN" type="xs:string" />
				<xs:element name="price" type="xs:double" />
				<xs:element name="url" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:attributeGroup name="att">
        <xs:attribute name="tel" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="qq" type="xs:integer"></xs:attribute>
		<xs:attribute name="msn" type="xs:string"></xs:attribute>
	</xs:attributeGroup>

</xs:schema>

=== jtlai0921/PB1436--600-Java----part05-ch15_ch17-/PB1224-5/CH16/462/xmldemo/xsd/attributeGroup_demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns="http://www.mingrisoft.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mingrisoft.com attributeGroup_demo.xsd">

	<name>《C#從入門到精通(第2版)》</name>
	<publisher>清華大學出版社</publisher>
	<company>明日科技</company>
	<author msn="wangxiaoke@mingrisoft.com" qq="200958602" tel="0431-84978981">王小科
	</author>
	<ISBN>9787302226628</ISBN>
	<price>2.0</price>
	<url>http://www.mingribook.com/bookinfo.php?id=227</url>
</book>
