=== jtlai0921/PB1436--600-Java----part05-ch15_ch17-/PB1224-5/CH15/436/xmldemo/dtd/entity_demo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT books (book+)>

<!ELEMENT book    (name,publisher,company,author,ISBN,price,url,type)>

<!ELEMENT name      (#PCDATA)>
<!ELEMENT publisher    (#PCDATA)>
<!ELEMENT company 	(#PCDATA)>
<!ELEMENT author    (#PCDATA)>
<!ELEMENT ISBN    (#PCDATA)>
<!ELEMENT price    (#PCDATA)>
<!ELEMENT url    (#PCDATA)>
<!ELEMENT type    (#PCDATA)>

<!ENTITY info "軟體專案師入門叢書" >

=== jtlai0921/PB1436--600-Java----part05-ch15_ch17-/PB1224-5/CH15/436/xmldemo/dtd/entity_demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "entity_demo.dtd">
<books>

	<book>
		<name>《Java從入門到精通（第2版）》</name>
		<publisher>清華大學出版社</publisher>
		<company>明日科技</company>
		<author>李鍾蔚</author>
		<ISBN>9787302227465</ISBN>
		<price>59.80</price>
		<url><![CDATA[http://www.mingribook.com/bookinfo.php?id=222]]></url>
		<type>&info;</type>
	</book>
</books>
