=== jtlai0921/PB1436--600-Java----part05-ch15_ch17-/PB1224-5/CH15/435/xmldemo/dtd/tel_demo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT book (name,publisher,company,author,ISBN,price,url,(tel|phone))>
<!ELEMENT name      (#PCDATA)>
<!ELEMENT publisher    (#PCDATA)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT author    (#PCDATA)>
<!ELEMENT ISBN    (#PCDATA)>
<!ELEMENT price    (#PCDATA)>
<!ELEMENT url    (#PCDATA)>
<!ELEMENT tel    (#PCDATA)>
<!ELEMENT phone    (#PCDATA)>

=== jtlai0921/PB1436--600-Java----part05-ch15_ch17-/PB1224-5/CH15/435/xmldemo/dtd/tel_demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "tel_demo.dtd">
<book>
	<name>《C#從入門到精通(第2版)》</name>
	<publisher>清華大學出版社</publisher>
	<company>明日科技</company>
	<author>王小科</author>
	<ISBN>9787302226628</ISBN>
	<price>69.80</price>
	<url><![CDATA[http://www.mingribook.com/bookinfo.php?id=227&sid=4]]></url>
	<tel>13812345678</tel>
</book>
