=== jtlai0921/PB1436--600-Java----part05-ch15_ch17-/PB1224-5/CH15/443/xmldemo/dtd/attlist_idref_demo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT books (book+)>

<!ELEMENT book    (name,publisher,company,author,ISBN,price,url,relevance*)>

<!ELEMENT name      (#PCDATA)>
<!ELEMENT publisher    (#PCDATA)>
<!ELEMENT company 	(#PCDATA)>
<!ELEMENT author    (#PCDATA)>
<!ELEMENT ISBN    (#PCDATA)>
<!ELEMENT price    (#PCDATA)>
<!ELEMENT url    (#PCDATA)>
<!ELEMENT relevance    (#PCDATA)>

<!ATTLIST book UID ID #REQUIRED>
<!ATTLIST relevance relUID IDREF #REQUIRED>

=== jtlai0921/PB1436--600-Java----part05-ch15_ch17-/PB1224-5/CH15/443/xmldemo/dtd/attlist_idref_demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "attlist_idref_demo.dtd">
<books>
	<book UID="AAAA">
		<name>《C#從入門到精通(第2版)》</name>
		<publisher>清華大學出版社</publisher>
		<company>明日科技</company>
		<author>王小科</author>
		<ISBN>9787302226628</ISBN>
		<price >69.80</price>
		<url><![CDATA[http://www.mingribook.com/bookinfo.php?id=227&sid=4]]></url>
	</book>
	<book UID="AAAB">
		<name>《JavaScript開發技術大全》</name>
		<publisher>人民郵電出版社</publisher>
		<company>明日科技</company>
		<author>梁冰</author>
		<ISBN>9787115179708</ISBN>
		<price>65.00</price>
		<url><![CDATA[http://www.mingribook.com/bookinfo.php?id=138&sid=5]]></url>
	</book>
	<book UID="AAAC">
		<name>《Java從入門到精通（第2版）》</name>
		<publisher>清華大學出版社</publisher>
		<company>明日科技</company>
		<author>李鍾蔚</author>
		<ISBN>9787302227465</ISBN>
		<price>59.80</price>
		<url><![CDATA[http://www.mingribook.com/bookinfo.php?id=222]]></url>
		<relevance relUID="AAAA">《C#從入門到精通(第2版)》</relevance>
	</book>
</books>
