<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  book [
	<!ELEMENT book (name,publisher,company,author,ISBN,price,url)>
	<!ELEMENT name      (#PCDATA)>
	<!ELEMENT publisher    (#PCDATA)>
	<!ELEMENT company (#PCDATA)>
	<!ELEMENT author    (#PCDATA)>
	<!ELEMENT ISBN    (#PCDATA)>
	<!ELEMENT price    (#PCDATA)>
	<!ELEMENT url    (#PCDATA)>
]>
<book>
	<name>《C#從入門到精通(第2版)》</name>
	<publisher>清華大學出版社</publisher>
	<company>明日科技</company>
	<author>王小科</author>
	<ISBN>9787302226628</ISBN>
	<price>69.80</price>
	<url><![CDATA[http://www.mingribook.com/bookinfo.php?id=227&sid=4]]></url>
</book>